### ISSUE TITLE
Create initial structure of TODO List Item

### ISSUE THREAD

**Issue by ShanMehr** [ianmccurry11/TODO_List#5]
Linked back to Issue https://github.com/ianmccurry11/TODO_List/issues/3 and https://github.com/ianmccurry11/TODO_List/issues/2

**Comment by ianmccurry11** [comment]
Linked back to Issue #3 and #2 
Include description
Include deadline
Include title

**Comment by ShanMehr** [comment]
Include description
Include deadline
Include title
Include location
Include status
include category
